import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "@/provider/UserProvider";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jamdani Cart",
  description: "Generated by create next app",
};

// DEBUG FETCH
// const originalFetch = global.fetch;

// global.fetch = async (...args) => {
//   console.log("🚨 FETCH CALL:", args[0]);
//   try {
//     const res = await originalFetch(...args);
//     console.log("✅ SUCCESS:", args[0]);
//     return res;
//   } catch (err) {
//     console.error("❌ FAILED FETCH:", args[0], err);
//     throw err;
//   }
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider>{children}</UserProvider>
        </ThemeProvider>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
